/* global process */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { FONT_JOBS, FONT_OUT_DIR, LATIN_TEXT } from '../../scripts/fonts/subset-fonts.mjs';

// Build-time font subsetting (scripts/fonts/subset-fonts.mjs + the vite
// plugin) pins each variable font's wght axis to the weights the site uses.
// This guard is the mirror of tests/unit/aosCss.spec.js: if a new font weight
// is added to src/ it must fall inside a pinned range (or the range must be
// extended in the same change) — otherwise the weight is synthesized or falls
// back and the subset is silently wrong.

// On Windows/vitest, import.meta.url is not a file:// URL — tests run from
// the project root, so process.cwd() is the reliable anchor.
const ROOT = process.cwd();
const SRC = join(ROOT, 'src');

// Tailwind weight utilities → numeric weight. font-Grotesk (a font-FAMILY
// utility) is intentionally not in this map.
const CLASS_WEIGHTS = {
  thin: 100,
  extralight: 200,
  light: 300,
  normal: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
  extrabold: 800,
  black: 900,
};

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) {
      // foces-webv23 is OFF-LIMITS (archived Sanity studio) — never scan it.
      if (entry.name !== 'foces-webv23') out.push(...walk(p));
    } else if (/\.(jsx?|css)$/.test(entry.name)) {
      out.push(p);
    }
  }
  return out;
}

function collectWeights() {
  const weights = new Set();
  for (const file of walk(SRC)) {
    const text = readFileSync(file, 'utf8');
    for (const [, cls] of text.matchAll(
      /font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black)\b/g,
    )) {
      weights.add(CLASS_WEIGHTS[cls]);
    }
    for (const [, n] of text.matchAll(/font-weight\s*:\s*(\d{3})\b/g)) {
      weights.add(Number(n));
    }
  }
  return weights;
}

let usedWeights;
let cssText;

beforeAll(() => {
  usedWeights = collectWeights();
  cssText = readFileSync(join(SRC, 'assets', 'fonts-latin.css'), 'utf8');
});

describe('font subsetting — pinned weight axes', () => {
  it('the subset script found the fontsource sources (guard is not vacuous)', () => {
    expect(FONT_JOBS.length).toBeGreaterThanOrEqual(2);
    expect(LATIN_TEXT.length).toBeGreaterThan(100);
  });

  it('every font weight used in src/ is inside a pinned axis range', () => {
    expect(usedWeights.size).toBeGreaterThan(0);
    // The union of the pinned ranges: Inter 300–800 covers Grotesk's 300–600.
    const min = Math.min(...FONT_JOBS.map((j) => j.axes.wght.min));
    const max = Math.max(...FONT_JOBS.map((j) => j.axes.wght.max));
    const outOfRange = [...usedWeights].filter((w) => w < min || w > max);
    expect(outOfRange).toEqual([]);
  });

  it('the CSS declared ranges match the script config (no drift)', () => {
    // Two @font-face blocks, in the same order as FONT_JOBS (inter, grotesk).
    const ranges = [...cssText.matchAll(/font-weight:\s*(\d+)\s+(\d+);/g)].map((m) => [
      Number(m[1]),
      Number(m[2]),
    ]);
    expect(ranges).toEqual(FONT_JOBS.map((j) => [j.axes.wght.min, j.axes.wght.max]));
  });

  it('the CSS references the generated subset files', () => {
    for (const job of FONT_JOBS) {
      expect(cssText).toContain(`../assets/fonts/${job.out}`);
    }
  });

  it('the generated subset files exist and are smaller than the sources (after a build)', () => {
    // Generated by the vite plugin on every build/dev — skip if no build has
    // run yet (the weight-usage guard above is the always-on check).
    for (const job of FONT_JOBS) {
      const subsetPath = join(FONT_OUT_DIR, job.out);
      let subsetSize;
      try {
        subsetSize = statSync(subsetPath).size;
      } catch {
        continue; // no build yet — fine
      }
      const srcSize = statSync(job.src).size;
      expect(subsetSize).toBeLessThan(srcSize);
    }
  });
});
